ServerName localhost

<VirtualHost *:80>
    # Hanya folder public/ yang bisa diakses dari browser
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        # Izinkan .htaccess (rewrite semua URL ke index.php)
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
