name: ordina-sonar
services:
  sonarqube:
    image: sonarqube:26.9.0.129388-community
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
